### ISSUE TITLE
Sub-optimal / not solution to R1 U1 F1

### ISSUE THREAD

**Issue by jm493** [hkociemba/RubiksCube-TwophaseSolver#15]
I discovered this problem on my CUBOTino autonomous
Orientate the cube with Green F, White U
R1 U1 F1
```
Cube status (via BGR color distance): UUUUUULLDFBBFRRFRRFFRFFRDDRRRUDDBDDBFFDLLDLLBLLLUBBUBB
Camera warm-up, camera setting, cube status (BGR), and solution, in: 50.0 secs

Cube solution: 9 moves  F3 U1 D2 R2 L2 U2 D2 R1 L2
Robot moves string: applied optimization type 2
Total robot movements: 47

total amount of servo movements: 47
```
And it DOESN'T SOLVE

Testing just the RubikTwoPhase library:

On Pi Zero W
(Andrea Favero bult the code code, possibly on a Pi Zero 2 W, in case that is significant)
```
(.virtualenvs) root@cubotino:/home/pi/cubotino/src# python
Python 3.7.3 (default, Oct 31 2022, 14:04:00)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twophase.solver  as sv
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
loading corner sym-tables...
loading move_twist table...
loading move_flip table...
loading move_slice_sorted table...
loading move_u_edges table...
loading move_d_edges table...
loading move_ud_edges table...
loading move_corners table...
loading phase1_prun table...
loading phase2_prun table...
loading phase2_cornsliceprun table...
>>> cubestring = 'UUUUUULLDFBBFRRFRRFFRFFRDDRRRUDDBDDBFFDLLDLLBLLLUBBUBB'
>>> sv.solve(cubestring,19,2)                                            
'F3 U1 D2 R2 L2 U2 D2 R1 L2 (9f)'
>>> 

(.virtualenvs) root@cubotino:/home/pi/cubotino/src# pip list | grep RubikTwoPhase
RubikTwoPhase         1.0.9

(.virtualenvs) root@cubotino:/home/pi/cubotino/src# uname -a
Linux cubotino 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv6l GNU/Linux
(.virtualenvs) root@cubotino:/home/pi/cubotino/src# cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 797.66
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 0000000083b98790
Model           : Raspberry Pi Zero W Rev 1.1
```

On Mac
```
(CUBOTino_venv) porta-mac:PC_files johnm$ python
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import twophase.solver as sv
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
loading corner sym-tables...
loading move_twist table...
loading move_flip table...
loading move_slice_sorted table...
loading move_u_edges table...
loading move_d_edges table...
loading move_ud_edges table...
loading move_corners table...
loading phase1_prun table...
loading phase2_prun table...
loading phase2_cornsliceprun table...
loading phase2_edgemerge table...
>>> cubestring = 'UUUUUULLDFBBFRRFRRFFRFFRDDRRRUDDBDDBFFDLLDLLBLLLUBBUBB'
>>> sv.solve(cubestring,19,2)
'F3 U3 R1 U2 D2 R2 L2 U2 D2 L2 (10f)'
>>> 
(CUBOTino_venv) porta-mac:CUBOT johnm$ pip list | grep RubikTwoPhase
RubikTwoPhase 1.1.1
```
10 Moves, but it is a solution.

**Comment by jm493** [comment]
PS. Adding an extra twist: R1 U1 F1 L1
= BUUBUULLDFBBFRRFRRUFRUFRLDRFRUFDBDDBLLFLLFBDDLLDUBDUBR
-> Cube solution: 4 moves  L3 F3 U3 R3 
Solves optimally.

**Comment by AndreaFavero71** [comment]
@jm493, by manually applying F3 U1 D2 R2 L2 U2 D2 R1 L2 to a cube scrambled R1 U1 F1 the cube gets correctly solved.
Thanks to your note I have found a semantic error in the optim_moves2 function of the Cubotino autonomous robot, that was preventing the robot from correctly solving the cube. I have just released the correction.
I cannot comment on the RubikTwoPhase returning less moves when running on a Raspberry Pi Zero2 compared to a Mac, by providing the same timeout.

**Comment by jm493** [comment]
@AndreaFavero71 Thanks. I see now.
Re-orientate the cube from its post-scan position back to its starting position before applying the moves.

I have installed your latest code, and it generated the same 9-move solution, which the robot applied to correctly solve the cube.
So, the "not solution" part of this issue is solved, we still have the 9-move / 10-move suboptimal answer issue.

**Comment by hkociemba** [comment]
sv.solve(cubestring,19,2) has no issue at all.
In the documentation you can read:

This solves the cube described by the definition string with a desired maximum length of 19 moves and a timeout of 2 seconds. If the timeout is reached, the shortest solution computed so far is returned even if it is longer than the desired maximum length.

So your desired maximum length is 19 and the returned solution with 10 moves is within this specification. If a solution with <=19 moves is found this is returned immediately no matter if there are any shorter solutions which might be found within your 2 s timelimit. So you should use  sv.solve(cubestring,0,2) or even   sv.solve(cubestring,0,0.1) for example and the 3 move solution is returned.
